/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "BIT_MATH.h"
#include "STD_TYPES.h"
#include "RCC_init.h"
#include "GPIO_init.h"
#include "NVIC_init.h"
#include "EXTI_interface.h"
#include "AFIO_init.h"
#include "GPIO_private.h"
//#include "IR_init.h"

void PUSH_BUTTON(void);

u8 button_state = 0;
int main(void)
{
	RCC_u8SetClkSource(RCC_HSE);
	RCC_u8SetClkStatus(RCC_HSE , 1);

	RCC_voidEnablePeripheralClock(RCC_APB2,APB2_GPIOB_EN);
	 RCC_voidEnablePeripheralClock(RCC_APB2,APB2_AFIO_EN);


	   GPIO_voidSetPinDirection(GPIOB , PIN5, OUTPUT_2MHZ_PUSH_PULL);
	   GPIO_voidSetPinValue(GPIOB , PIN5, LOW);

	   /* set the dirction of IR pin => input floating for EXTI */
	   GPIO_voidSetPinDirection(GPIOB,PIN0,INPUT_FLOATING);


	EXTI_voidInit(EXTI_LINE0,ON_CHANGE);
	AFIO_voidSetEXTIConfiguration(AFIO_EXTI_LINE0,AFIO_EXTI_PORTB);

    /* enable interrupt */
    EXTI_voidSetCallBack(EXTI_LINE0,PUSH_BUTTON);
    NVIC_voidEnableInterrupt(EXTI0_IRQn);

	while(1){


		if (button_state==0){
			 GPIO_voidSetPinValue(GPIOB , PIN5, LOW);
		}
		else {
			 GPIO_voidSetPinValue(GPIOB , PIN5, HIGH);
		}
	}
	return 0;

}

void PUSH_BUTTON (void){

	TOG_BIT(button_state,0);

}
